LANGUAGE_MAP = {
    "English": "en-US",
    "German": "de-DE",
    "Italian": "it-IT",
    "French": "fr-FR",
    "Spanish": "es-ES",
    "Portuguese": "pt-PT",
    "Portuguese (Brazil)": "pt-BR",
    "Dutch": "nl-NL",
    "Danish": "da-DK",
    "Swedish": "sv-SE",
    "Norwegian": "nb-NO",
    "Finnish": "fi-FI",
    "Icelandic": "is-IS",
    "Greek": "el-GR",
    "Polish": "pl-PL",
    "Czech": "cs-CZ",
    "Slovak": "sk-SK",
    "Hungarian": "hu-HU",
    "Romanian": "ro-RO",
    "Bulgarian": "bg-BG",
    "Croatian": "hr-HR",
    "Serbian": "sr-RS",
    "Slovenian": "sl-SI",
    "Bosnian": "bs-BA",
    "Albanian": "sq-AL",
    "Macedonian": "mk-MK",
    "Montenegrin": "sr-ME",
    "Estonian": "et-EE",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Irish": "ga-IE",
    "Scottish Gaelic": "gd-GB",
    "Welsh": "cy-GB",
    "Maltese": "mt-MT",
    "Luxembourgish": "lb-LU",
    "Belarusian": "be-BY",
    "Ukrainian": "uk-UA",
    "Russian": "ru-RU",  # Partly European
    "Turkish": "tr-TR",  # Partly European
    # Non-European examples for completeness
    "Hindi": "hi-IN",
}